# This playbook create a Key Vault which is not available in v2.4, so you need to run "ansible-galaxy install Azure.azure_preview_modules" to install the role to get lastest Ansible modules.
# Change variables below to customize environment.
# Run "ansible-playbook KeyVaultCreate.yml" to execute this playbook
---
- hosts: localhost
  roles:
    - Azure.azure_preview_modules
  vars:
    resource_group: ansibledemokeyvault
    location: eastus
    keyvault_name: keyvaultansible
    object_id: 97567bfa-cf13-4217-8fa3-cc56bc1867fe
  tasks:
    - name: Create a resource group
      azure_rm_resourcegroup:
        name: "{{ resource_group }}"
        location: "{{ location }}"

    - name: Create instance of Key Vault
      azure_rm_keyvault:
        resource_group: "{{ resource_group }}"
        vault_name: "{{ keyvault_name }}"
        enabled_for_deployment: yes
        sku:
          name: standard
          family: A
        access_policies:
          - object_id: "{{ object_id }}"
            keys:
              - get
              - list
              - update
              - create
              - import
              - delete
              - recover
              - backup
              - restore
            secrets:
              - get
              - list
              - set
              - delete
              - recover
              - backup
              - restore

    - name: create a kevyault key
      block:
        - azure_rm_keyvaultkey:
            keyvault_uri: https://{{ keyvault_name }}.vault.azure.net
            key_name: testkey
            tags:
              testing: test
              delete: on-exit
          register: output
        - assert:
            that: output.changed
      rescue:
        - azure_rm_keyvaultkey:
            keyvault_uri: https://{{ keyvault_name }}.vault.azure.net
            state: absent
            key_name: testkey

    - name: create a kevyault secret
      block:
        - azure_rm_keyvaultsecret:
            keyvault_uri: https://{{ keyvault_name }}.vault.azure.net
            secret_name: testsecret
            secret_value: 'mysecret'
