# Description
# ===========
# Use this playbook to ping all the Virtual Machines in VMSS.
# Use vmss-create playbook to create VMSS first
# This sample requires Ansible 2.6 

---
- hosts: localhost
  vars:
    resource_group: zimsvmssrg
    scaleset_name: zimsvmss
    loadbalancer_name: zimsvmsslb

  tasks:   
    - include: get-hosts-tasks.yml

- hosts: scalesethosts
  tasks: 
    - name: Ping specific host
      ping:
