---
- hosts: localhost
  roles:
    - updatingvmss
  vars:
    resource_group: zimsvmssrg
  tasks: 
    - name: Get scaleset info
      azure_rm_virtualmachine_scaleset_facts:
        resource_group: zimsvmssrg
        name: zimsvmss
        format: full
      register: output_scaleset

    - name: Dump scaleset info
      debug:
        var: output_scaleset


    #- name: Get subnet id
    #  set_fact:
    #    sp: "{{ output_scaleset.ansible_facts.azure_vmss[0].properties.virtualMachineProfile.networkProfile.networkInterfaceConfigurations[0].properties.ipConfigurations[0].properties.subnet.id }}"
    #    lbbapp: "{{ output_scaleset.ansible_facts.azure_vmss[0].properties.virtualMachineProfile.networkProfile.networkInterfaceConfigurations[0].properties.ipConfigurations[0].properties.loadBalancerBackendAddressPools[0].id }}"

    #- name: Extract virtual network name and subnet name
    #  set_fact:
    #    virtual_network_name: "{{ sp | regex_replace('.*virtualNetworks\\/') | regex_replace('\\/subnets.*')}}"
    #    subnet_name: "{{ sp | regex_replace('.*subnets\\/') }}"
    #    load_balancer: "{{ lbbapp | regex_replace('.*loadBalancers\\/') | regex_replace('\\/backendAddressPools.*')}}"

    #- name: Update something in that VMSS
    #  azure_rm_virtualmachine_scaleset:
    #    resource_group: "{{ resource_group }}"
    #    name: "{{ output_scaleset.ansible_facts.azure_vmss[0].name }}"
    #    state: present
    #    location: "{{ output_scaleset.ansible_facts.azure_vmss[0].location }}"
    #    vm_size: "{{ output_scaleset.ansible_facts.azure_vmss[0].sku.name }}"
    #    capacity: 3 #"{{ output_scaleset.ansible_facts.azure_vmss[0].sku.capacity }}"
    #    tier: "{{ output_scaleset.ansible_facts.azure_vmss[0].sku.tier }}"
    #    upgrade_policy: Automatic #"{{ output_scaleset.ansible_facts.azure_vmss[0].properties.upgradePolicy.mode }}"
        #admin_username: zim
        #admin_password: MyPassword123!!!
        #ssh_password_enabled:
        #ssh_public_keys:
    #    image:
    #      offer: "{{ output_scaleset.ansible_facts.azure_vmss[0].properties.virtualMachineProfile.storageProfile.imageReference.offer }}"
    #      publisher: "{{ output_scaleset.ansible_facts.azure_vmss[0].properties.virtualMachineProfile.storageProfile.imageReference.publisher }}"
    #      sku: "{{ output_scaleset.ansible_facts.azure_vmss[0].properties.virtualMachineProfile.storageProfile.imageReference.sku }}"
    #      version: "{{ output_scaleset.ansible_facts.azure_vmss[0].properties.virtualMachineProfile.storageProfile.imageReference.version }}"
    #    os_disk_caching: "{{ output_scaleset.ansible_facts.azure_vmss[0].properties.virtualMachineProfile.storageProfile.osDisk.caching }}"
    #    os_type: Linux
    #    managed_disk_type: "{{ output_scaleset.ansible_facts.azure_vmss[0].properties.virtualMachineProfile.storageProfile.osDisk.managedDisk.storageAccountType }}"
    #    data_disks: []
        #  - lun: 0
        #    disk_size_gb: 64
        #    managed_disk_type: "{{ output_scaleset.ansible_facts.azure_vmss[0].properties.virtualMachineProfile.storageProfile.osDisk.managedDisk.storageAccountType }}"
        #    caching: "{{ output_scaleset.ansible_facts.azure_vmss[0].properties.virtualMachineProfile.storageProfile.osDisk.caching }}"
        #virtual_network_resource_group:
    #    virtual_network_name: "{{ virtual_network_name }}"
    #    subnet_name: "{{ subnet_name }}"
    #    load_balancer: "{{ load_balancer }}"
        #remove_on_absent:

    - name: Update something in that VMSS
      azure_rm_virtualmachine_scaleset: "{{ output_scaleset.ansible_facts.azure_vmss[0] }}"
      
    #    resource_group: "{{ resource_group }}"
    #    name: "{{ output_scaleset.ansible_facts.azure_vmss[0].name }}"
    #    state: present
    #    location: "{{ output_scaleset.ansible_facts.azure_vmss[0].location }}"
    #    vm_size: "{{ output_scaleset.ansible_facts.azure_vmss[0].sku.name }}"
    #    capacity: 3 #"{{ output_scaleset.ansible_facts.azure_vmss[0].sku.capacity }}"
    #    tier: "{{ output_scaleset.ansible_facts.azure_vmss[0].sku.tier }}"
    #    upgrade_policy: Automatic #"{{ output_scaleset.ansible_facts.azure_vmss[0].properties.upgradePolicy.mode }}"
        #admin_username: zim
        #admin_password: MyPassword123!!!
        #ssh_password_enabled:
        #ssh_public_keys:
    #    image:
    #      offer: "{{ output_scaleset.ansible_facts.azure_vmss[0].properties.virtualMachineProfile.storageProfile.imageReference.offer }}"
    #      publisher: "{{ output_scaleset.ansible_facts.azure_vmss[0].properties.virtualMachineProfile.storageProfile.imageReference.publisher }}"
    #      sku: "{{ output_scaleset.ansible_facts.azure_vmss[0].properties.virtualMachineProfile.storageProfile.imageReference.sku }}"
    #      version: "{{ output_scaleset.ansible_facts.azure_vmss[0].properties.virtualMachineProfile.storageProfile.imageReference.version }}"
    #    os_disk_caching: "{{ output_scaleset.ansible_facts.azure_vmss[0].properties.virtualMachineProfile.storageProfile.osDisk.caching }}"
    #    os_type: Linux
    #    managed_disk_type: "{{ output_scaleset.ansible_facts.azure_vmss[0].properties.virtualMachineProfile.storageProfile.osDisk.managedDisk.storageAccountType }}"
    #    data_disks: []
        #  - lun: 0
        #    disk_size_gb: 64
        #    managed_disk_type: "{{ output_scaleset.ansible_facts.azure_vmss[0].properties.virtualMachineProfile.storageProfile.osDisk.managedDisk.storageAccountType }}"
        #    caching: "{{ output_scaleset.ansible_facts.azure_vmss[0].properties.virtualMachineProfile.storageProfile.osDisk.caching }}"
        #virtual_network_resource_group:
    #    virtual_network_name: "{{ virtual_network_name }}"
    #    subnet_name: "{{ subnet_name }}"
    #    load_balancer: "{{ load_balancer }}"
        #remove_on_absent:
