---
- hosts: localhost
  roles:
    - resourcesupport
  vars:
    resource_group: zimsvmss
    scaleset_name: zimsvmss
    loadbalancer_name: zimsvmsslb

  tasks:   

    - name: Call REST API - ResourceGroups_ExportTemplate
      azure_rm_resource:
        url: /subscriptions/{{ lookup('env','AZURE_SUBSCRIPTION_ID') }}/resourcegroups/{{ resource_group }}/exportTemplate
        api_version: '2018-02-01'
        method: POST
        body:
          # Export resource group template request parameters.
          resources:
            - "*"
      register: output
    
    - name: Dump template
      debug:
        var: output
        